name: test tag deletion
on:
  - delete

jobs:
  test-deletion:
    runs-on: macos-10.15
    steps:
      - name: check event
        run: |
          echo ${{ github.event.ref }}
          echo ${{ github.event.ref_type }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: restore tag
        run: |
          git fsck --unreachable | grep tag
          git update-ref refs/tags/${{ github.event.ref }}