name: test tag deletion
on:
  - delete

jobs:
  test-deletion:
    runs-on: macos-10.15
    steps:
      - name: check event
        run: |
          echo ${{ github.event.ref }}
          echo ${{ github.event.repository.commits_url }}
          echo ${{ github.event.repository.git_commits_url }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: restore tag
        run: |
          git tag -a ${{ github.event.ref }} ${{ github.event.repository.commits_url }} -m "${{ github.event.ref }}"
          git push origin ${{ github.event.ref }}