name: test tag deletion
on:
  - delete

jobs:
  test-deletion:
    runs-on: macos-10.15
    steps:
      - name: check event
        run: |
          echo ${{ github.event.ref }}
          for i in ${{ github.event }}
          do
              echo "key: $i"
              echo "value: ${arr[$i]}"
          done
      - name: Checkout code
        uses: actions/checkout@v2
      - name: restore tag
        run: |
          # git tag -a ${{ github.event.ref }} ${{ github.event.repository.commits_url }} -m "${{ github.event.ref }}"
          # git push origin ${{ github.event.ref }}